### ISSUE TITLE
Create Search layout

### ISSUE THREAD

**Issue by ubergonmx** [ubergonmx/newsmead#4]
Lo-Fi Layout
<img src="https://github.com/ubergonmx/newsmead/assets/73865149/42276d43-cf8b-4662-8371-f8c4a6f63f1c" width=500 />

**Comment by erik-lance** [comment]
Layout was set up at 07e7a3a7ce8f791ee897520410e07467a7727dc8

**Comment by erik-lance** [comment]
Chips were created  for the category and sources chip groups. This has been successfully implemented by d24f69ee85cdc12a429d219f9d510fcae1040d1c
