### ISSUE TITLE
Organize Kotlin classes & layouts

### ISSUE THREAD

**Issue by ubergonmx** [ubergonmx/newsmead#7]

**Comment by erik-lance** [comment]
Added sample package structure at 4229f3ab7655ab8c73dbd04c6728c0f77060b331

Let's do

.
└── NewsMead/
    └── recyclerviews/
        ├── feed/
        │   ├── feedAdapter
        │   └── feedViewHolder
        └── search/
            ├── searchAdapter
            └── searchViewHolder
